import React, { useMemo, useState } from 'react';

import { DAOItem } from '../components/DAOItem';
import { H1 } from '../components/H1';
import { SearchField } from '../components/Searchfield';
import { useDAOs } from '../hooks/useDAOs';

import type { NextPage } from 'next'
const Home: NextPage = () => {
  const [searchText, setSearchText] = useState('')

  const { data: DAOs } = useDAOs()

  const filteredData = useMemo(() => {
    return searchText === ''
      ? DAOs
      : DAOs?.filter(({ name }) =>
          name.toLowerCase().includes(searchText.toLowerCase()),
        )
  }, [searchText, JSON.stringify(DAOs)])

  return (
    <div className="flex flex-col gap-4">
      <div className="flex justify-between">
        <H1>DAOs</H1>
        <div className="flex gap-4">
          <SearchField
            placeholder="Search DAOs..."
            onChange={(e) => setSearchText(e.currentTarget.value)}
          />
        </div>
      </div>
      <div className="grid gap-4 grid-cols-2 md:grid-cols-4 lg:grid-cols-5">
        {filteredData?.map((props) => (
          <DAOItem key={props.id} {...props} />
        ))}
      </div>
    </div>
  )
}

export default Home
/* Qiao Wen's Code */
// import {
//   WalletDisconnectButton,
//   WalletMultiButton,
// } from "@solana/wallet-adapter-react-ui";
// import type { NextPage } from "next";
// import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
// import QwComponent from "./components/QwComponent";

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <QwComponent />
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <div className={styles.walletButtons}>
//           <WalletMultiButton />
//           <WalletDisconnectButton />
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{" "}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   );
// };

// export default Home;
